services:
  backend:
    build:
      context: ./backend
    ports:
      - "5005:5005"
    environment:
      - PORT=5005

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - backend
